name: 'Dear Santa Action'
description: 'Write to Santa and he\'ll respond with just the right Christmas greeting 🎅'
branding:
  icon: 'gift'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
